version: '3'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.docker
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "host=localhost"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.docker
    working_dir: /var/www
    volumes_from:
      - app
    links:
      - app
    ports:
      - 8001:80

  composer:
    restart: 'no'
    image: composer
    command: install
    volumes_from:
      - app
    working_dir: /var/www

  node:
    image: "node:12.14"
    working_dir: /var/www
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/var/www
    expose:
      - "8001"
    command: bash -c "npm install && npm run watch-poll"

  # The Database
  database:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
        - "33062:3306"

volumes:
  db: